/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package am.aua.sas.jirc;

import am.aua.sas.jirc.gui.JircGUI;

public class Main {
	public static void main(String[] args) {
		JircGUI gui = new JircGUI();
	}
}
